### ISSUE TITLE
self_service_portal

### ISSUE THREAD

**Issue by mhmdio** [cloudposse/terraform-aws-ec2-client-vpn#34]
Have a question? Please check out our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

[self_service_portal](https://registry.terraform.io/providers/hashicorp/aws/3.74.3/docs/resources/ec2_client_vpn_endpoint#self_service_portal) - (Optional) Specify whether to enable the self-service portal for the Client VPN endpoint. Values can be enabled or disabled. Default value is disabled.

**Comment by nitrocode** [comment]
@mhmdio could you try the pr branch out to see if it works for you?

```hcl
module "client_vpn" {
  source = "git::https://github.com/cloudposse/terraform-aws-ec2-client-vpn.git?ref=portal"

  # ...
}
```
